/* v27.8 算数全学年 共通完成フロー */
const MATHRET278="ponoMathBridgeRetention278"; let mb278=null;
function q278(title){
 const q={"割合":[["割合を求める式は？",["くらべる量÷もとにする量","たすだけ","もとにする量÷くらべる量"],0],["100%は？",["全体","半分","2倍"],0],["50人の40%は？",["20人","10人","40人"],0]],"平均":[["10,20,30の平均は？",["20","30","60"],0],["平均は合計を何で割る？",["個数","最大値","最小値"],0],["4人の合計80なら平均は？",["20","40","10"],0]],"文字と式":[["分からない数を表すのに使えるのは？",["文字","色だけ","時刻だけ"],0],["x+3でx=2なら？",["5","3","6"],0],["a×4は？",["aの4倍","a+4だけ","4÷aだけ"],0]]};
 if(q[title])return q[title];
 let d=mb260data(title);return [[`「${title}」で最初に確認したいのは？`,["分かっていることと求めること","答えだけ","文字の色"],0],[d[1],["説明や図・式を使って確かめる","数字を見ずに決める","必ず飛ばす"],0],["途中で分からなくなったら？",["①まなぶや②一緒に戻る","適当に決める","そのまま終わる"],0]];
}
function home278(g,t){mb278={g,t,i:0,ok:0,h:0,start:Date.now(),qs:q278(t)};let d=mb260data(t);head(`算数｜${t}`,()=>subjectGradeTerms("算数",g));A.append(e("div","card",`<h2>${t}</h2><p>${d[0]}</p>`));A.append(btn("📖 ①まなぶ",()=>learn278(g,t),"primary"));A.append(btn("🚀 問題からやってみる",()=>self278(g,t),"soft"))}
function learn278(g,t){let d=mb260data(t);head(`①まなぶ｜${t}`,()=>home278(g,t));A.append(e("div","card lesson",`<h2>考え方</h2><p>${fmtMath(d[0])}</p><p>${fmtMath(d[1])}</p>`));A.append(btn("🔊 説明を聞く",()=>speakLesson(t+"。"+d[0]+"。"+d[1]),"soft"));A.append(btn("➡️ ② 一緒にやってみる",()=>together278(g,t),"primary"))}
function together278(g,t){let q=mb278.qs[0],d=mb260data(t);head(`②一緒に｜${t}`,()=>learn278(g,t));A.append(e("div","card lesson",`<h2>一緒に考えよう</h2><p>① ${fmtMath(q[0])}</p><p>② ${fmtMath(d[1])}</p><p>③ 答え：<b>${fmtMath(q[1][q[2]])}</b></p>`));A.append(btn("③ 自分でやってみる",()=>self278(g,t),"primary"))}
function self278(g,t){let q=mb278.qs[mb278.i];head(`③自分で｜${t}`,()=>together278(g,t));A.append(e("div","tiny",`${mb278.i+1} / ${mb278.qs.length}`));A.append(e("div","card",`<h2>${fmtMath(q[0])}</h2>`));q[1].forEach((x,i)=>{let b=btn("",()=>{if(i===q[2]){mb278.ok++;mb278.i++;if(mb278.i<mb278.qs.length)self278(g,t);else summary278(g,t)}else{mb278.h++;A.prepend(e("div","feedback warn","🌱 説明や図・式をもう一度見てみよう。"))}},"soft");b.innerHTML=fmtMath(x);A.append(b)});A.append(btn("💡 説明を見る",()=>{mb278.h++;learn278(g,t)},"ghost"))}
function summary278(g,t){let total=mb278.qs.length,rate=Math.round(mb278.ok/total*100);records.push({studentId:profile.id,date:new Date().toISOString(),subject:"算数",grade:g,unit:t,rate,correct:mb278.ok,total,seconds:Math.round((Date.now()-mb278.start)/1000),hints:mb278.h,status:"学習済み",next:"定着確認"});save();head(`まとめ｜${t}`,()=>home278(g,t));A.append(e("div","card good",`<h2>まとめまでできました 🌱</h2><p>${mb278.ok} / ${total}</p>`));A.append(btn("🌱 単元ふりかえり",()=>reflect278(g,t),"primary"))}
function reflect278(g,t){head(`🌱ふりかえり｜${t}`,()=>summary278(g,t));["😊 わかった","🧮 式があると分かりやすい","🖼️ 図があると分かりやすい","🔊 聞くと分かりやすい","🤝 一緒にもう一度やりたい"].forEach(v=>A.append(btn(v,()=>retain278(g,t,v),"soft")))}
function retain278(g,t,v){let q=q278(t)[1]||q278(t)[0];head(`🕰️ 定着確認｜${t}`,()=>subjectGradeTerms("算数",g));A.append(e("div","card",`<h2>あとから確認</h2><p>できれば別の日に、もう一度確認します。</p><h3>${fmtMath(q[0])}</h3>`));q[1].forEach((x,i)=>{let b=btn("",()=>{let a=[];try{a=JSON.parse(localStorage.getItem(MATHRET278)||"[]")}catch(e){};a.push({studentId:profile.id,date:new Date().toISOString(),grade:g,unit:t,retained:i===q[2],reflection:v});localStorage.setItem(MATHRET278,JSON.stringify(a));head("🌱確認できました",()=>subjectGradeTerms("算数",g));A.append(btn("単元一覧へ",()=>subjectGradeTerms("算数",g),"primary"))},"soft");b.innerHTML=fmtMath(x);A.append(b)})}
/* 詳細教材がある単元は既存教材を優先。ない単元だけ共通フローで補完 */
mathTextbookOpen249=function(g,t){const id=findMathNode249(g,t);if(id&&typeof beginMathUnit==="function"){beginMathUnit(id);return}home278(g,t)};
