/* v33.3 理科3〜6年：詳しい「学ぶ」＋単元テスト10問 */
const SCI_EXTRA333={"3|生き物をさがそう":"生き物は、食べ物・水・かくれる場所など、くらしやすい環境と関わっています。比べるときは、同じ広さ・同じ時間など条件をそろえます。","3|植物を育てよう":"芽が出たあと、子葉、葉、くき、根が育ちます。同じ植物を続けて、草丈や葉の数、花や実のでき方を記録すると成長の順序が分かります。","3|チョウを育てよう":"チョウは、たまご→幼虫→さなぎ→成虫の順に育ちます。見た目が大きく変わっても、日にちと姿をつなげて記録します。","3|風やゴムのはたらき":"風が強いほど、またゴムを大きくのばすほど、物を動かすはたらきが大きくなることがあります。調べたい条件だけを変えることが大切です。","3|こん虫のかんさつ":"こん虫の体は頭・むね・はらの3つに分かれ、6本のあしはすべてむねから出ます。羽がある場合も、羽はむねについています。","3|太陽とかげ":"かげは太陽の反対側にできます。太陽の位置が時間とともに変わるため、かげの向きや長さも変わります。","3|太陽の光":"日光はまっすぐ進み、鏡ではね返すことができます。日光が当たる場所は明るく、温度が高くなることがあります。","3|音のせいしつ":"音が出ている物はふるえています。ふるえが大きいほど音が大きくなることがあり、ふるえは空気や物を通して伝わります。","3|物の重さ":"同じ物なら形を変えても重さは変わりません。同じ体積でも、物の種類が違うと重さが違うことがあります。","3|電気の通り道":"豆電球は、乾電池・導線・豆電球が切れ目なくつながった回路で点灯します。金属には電気を通しやすい物が多くあります。","3|じしゃくのせいしつ":"じしゃくにはN極とS極があり、違う極は引き合い、同じ極はしりぞけ合います。鉄などを引きつける性質もあります。","4|あたたかくなると":"春に向かって気温が上がると、植物の芽や葉が育ち、動物の活動も見られるようになります。同じ場所を継続して観察します。","4|動物のからだのつくりと運動":"骨は体を支え、関節で曲げ伸ばしができます。筋肉が縮んだりゆるんだりすることで骨が動きます。","4|天気と気温":"晴れの日は朝から昼に向けて気温が上がり、その後下がることが多くあります。くもりや雨では変化が小さい場合があります。","4|電流のはたらき":"乾電池の向きを変えると電流の向きも変わり、モーターの回る向きも変わります。乾電池の数やつなぎ方で電流の大きさも変わります。","4|雨水のゆくえ":"雨水は高い所から低い所へ流れ、低い所に集まります。土の種類によって、水のしみこみ方も違います。","4|暑くなると":"夏に向かって気温が高くなると、植物の成長や動物の活動がさかんになります。春からの観察記録と比べます。","4|月や星":"月や星は時間とともに位置が変わって見えます。星の並び方はほぼ変わらないまま、空の中を移動して見えます。","4|とじこめた空気と水":"閉じこめた空気は押すと体積が小さくなり、押し返す力が大きくなります。水は空気ほど縮みません。","4|物の体積と温度":"空気・水・金属は温度によって体積が変わります。多くの場合、温めると大きくなり、冷やすと小さくなります。","4|物のあたたまり方":"金属は熱した所から順に熱が伝わります。水や空気は、温められた部分が動くことで全体が温まります。","4|水のすがたと温度":"水は0℃付近で氷になり、100℃付近で沸騰して水蒸気になります。温度と水の姿を一緒に記録します。","4|生き物の1年":"生き物のようすは春・夏・秋・冬で変わります。一年分の観察記録をつなげると、気温と生き物の変化の関係が見えます。","5|天気の変化":"雲の量や動きは天気の変化と関係します。日本付近では天気が西から東へ変わることが多く、広い範囲の気象情報が予想に役立ちます。","5|植物の発芽と成長":"種子の発芽には水・適した温度・空気が必要です。発芽後の成長には日光や肥料が関係し、条件は一つずつ変えて調べます。","5|魚のたんじょう":"魚は受精卵から育ち、卵の中で目や体の形が少しずつできて、やがてふ化します。同じ卵を日を追って観察します。","5|花から実へ":"花粉がめしべの先につくことを受粉といいます。受粉したあと、めしべの一部が育って実や種子になります。","5|台風と防災":"台風は強い風や大雨をもたらします。進路・雨量・風の予報、警報、ハザードマップなどを使い、安全な行動につなげます。","5|流れる水のはたらき":"流れる水には、土地をけずる侵食、土砂を運ぶ運搬、土砂を積もらせる堆積のはたらきがあります。","5|物のとけ方":"物が水にとけてもなくなるわけではなく、水の中に存在しています。とかす前後で全体の重さは変わりません。","5|人のたんじょう":"胎児は子宮の中で育ち、胎盤とへその緒を通して酸素や養分を受け取ります。成長のようすを資料から読み取ります。","5|電流がうみ出す力":"コイルに電流を流すと電磁石になります。電流を大きくしたり巻き数を増やしたりすると、磁力が強くなる傾向があります。","6|物の燃え方と空気":"物が燃えるとき酸素が使われ、燃えた後は酸素が減り二酸化炭素が増えます。燃え続けるには新しい空気の供給が必要です。","6|動物のからだのはたらき":"食べ物は消化・吸収され、呼吸で取り入れた酸素とともに血液で全身へ運ばれます。心臓は血液を送り出します。","6|植物のからだのはたらき":"植物は根から水を取り入れ、茎を通して葉へ運びます。葉では日光を受けてでんぷんなどの養分をつくります。","6|生き物どうしのかかわり":"生き物は食べる・食べられる関係でつながり、空気・水などの環境とも関わっています。一つの変化が他の生き物へ影響することがあります。","6|月の形と太陽":"月は太陽の光を反射して光って見えます。太陽・月・地球の位置関係によって、地球から見える明るい部分が変わります。","6|大地のつくり":"大地には、れき・砂・泥・火山灰などが層になった地層があります。化石や地層の重なりから昔の環境を考えます。","6|変わり続ける大地":"地震や火山活動は大地を短い時間で変えることがあり、流水などは長い時間をかけて地形を変えます。防災にもつなげます。","6|てこのはたらき":"てこには支点・力点・作用点があります。支点から力点までの距離を長くすると、小さい力で物を動かしやすくなります。","6|電気と私たちのくらし":"電気は光・音・熱・運動などに変えることができ、つくった電気をためて使うこともできます。発電・蓄電・利用をつなげて考えます。","6|水溶液の性質とはたらき":"水溶液には酸性・中性・アルカリ性があります。リトマス紙などで性質を調べ、金属との反応も観察します。","6|地球に生きる":"人は空気・水・生き物などの環境と関わって暮らしています。資源を大切に使い、持続可能な方法をデータや事例から考えます。"};
const SCI_TERMS333={"3|こん虫のかんさつ":[["頭・むね・はら","こん虫の体の3つの部分。"],["6本のあし","すべてむねから出る。"]],"3|電気の通り道":[["回路","電気が通る一続きの道。"],["導線","電気を通すためにつなぐ線。"]],"3|じしゃくのせいしつ":[["N極・S極","じしゃくの2つの極。"],["極","じしゃくの力が強くはたらく端。"]],"4|とじこめた空気と水":[["体積","物が空間をしめる大きさ。"],["圧縮","押して体積を小さくすること。"]],"4|物のあたたまり方":[["伝導","熱した所から順に熱が伝わること。"],["対流","水や空気が動いて熱を運ぶこと。"]],"4|水のすがたと温度":[["水蒸気","目に見えない気体の水。"],["沸騰","液体の内部からもさかんに気体になる現象。"]],"5|植物の発芽と成長":[["発芽","種子から芽が出ること。"],["対照実験","一つの条件だけを変えて比べる実験。"]],"5|花から実へ":[["受粉","花粉がめしべの先につくこと。"],["花粉","おしべの先にできる粉状のもの。"]],"5|流れる水のはたらき":[["侵食","流れる水が土地をけずること。"],["運搬・堆積","土砂を運び、積もらせるはたらき。"]],"5|物のとけ方":[["水溶液","物が水にとけた液。"],["溶解","物が液体中に均一に広がること。"]],"5|電流がうみ出す力":[["コイル","導線を何回も巻いたもの。"],["電磁石","電流が流れている間、磁石の性質をもつもの。"]],"6|物の燃え方と空気":[["燃焼","物が酸素と反応して燃えること。"],["酸素","物を燃やすはたらきのある気体。"]],"6|動物のからだのはたらき":[["消化","食べ物を吸収しやすい形に変えること。"],["循環","血液が全身をめぐること。"]],"6|植物のからだのはたらき":[["蒸散","葉などから水が水蒸気として出ること。"],["でんぷん","植物がつくる養分の一つ。"]],"6|生き物どうしのかかわり":[["食物連鎖","食べる・食べられる関係のつながり。"],["生態系","生き物と環境がつながったまとまり。"]],"6|月の形と太陽":[["満月","月の明るい面がほぼ全面見える状態。"],["反射","光が物に当たりはね返ること。"]],"6|大地のつくり":[["地層","土砂や火山灰などが層になったもの。"],["化石","昔の生き物の体や生活のあと。"]],"6|てこのはたらき":[["支点","てこが動く中心の点。"],["力点・作用点","力を加える点と物に力がはたらく点。"]],"6|電気と私たちのくらし":[["発電","ほかのエネルギーから電気をつくること。"],["蓄電","電気をためること。"]],"6|水溶液の性質とはたらき":[["酸性","青色リトマス紙を赤に変える性質。"],["アルカリ性","赤色リトマス紙を青に変える性質。"]],"6|地球に生きる":[["資源","生活に利用する水・森林・エネルギーなど。"],["持続可能","将来も使い続けられるようにする考え方。"]]};
let sci333=null;
function sciBase333(g,t){
 if(g===3&&typeof SCI3_284!=="undefined"&&SCI3_284[t]){let d=SCI3_284[t];return {learn:d.learn,predict:d.predict,observe:d.observe,result:d.result,think:d.think,oldqs:d.qs||[]}}
 if(g>=4&&g<=6&&typeof SCI456_289!=="undefined"&&SCI456_289[String(g)]&&SCI456_289[String(g)][t]){let x=SCI456_289[String(g)][t];return {learn:x[0],predict:x[1],observe:x[2],result:x[3],think:x[4],oldqs:[]}}
 return null;
}
function sciData333(g,t){let b=sciBase333(g,t),k=`${g}|${t}`;if(!b||!SCI_EXTRA333[k])return null;return Object.assign(b,{extra:SCI_EXTRA333[k],terms:SCI_TERMS333[k]||[]})}
function sciEsc333(s){return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function sciVisual333(g,t){try{if(g===3&&typeof scienceVisual285==="function")return scienceVisual285(t)||"";if(g===3&&typeof scienceVisual241==="function")return scienceVisual241(t)||"";if(g>=4&&typeof sci289Visual==="function")return sci289Visual(String(g),t)||""}catch(e){}return ""}
function sciHome333(g,t,term){let d=sciData333(g,t);if(!d)return false;sci333={g,t,term,d,p:0,testI:0,testOk:0,mist:[],qs:null,start:0,saved:false};head(`理科｜${t}`,()=>subjectGradeTerms("理科",g));A.append(e("div","card",`<div class="tiny">理科｜小学${g}年</div><h2>${t}</h2>${sciVisual333(g,t)}<p><b>この単元で学ぶこと</b></p><p>${sciEsc333(d.learn)}</p><p>${sciEsc333(d.extra)}</p><p class="tiny">現行の学習内容に沿って、Ponoオリジナルの説明で整理しています。</p>`));A.append(btn("📘 ① 学ぶ",sciLearn333,"primary"));A.append(btn("🤝 ② 一緒に確認",sciTogether333,"soft"));A.append(btn("✏️ ③ 自分で確認",sciPractice333,"soft"));A.append(btn("📝 単元テスト（10問）",sciTestStart333,"primary"));return true}
function sciLearn333(){let s=sci333,d=s.d;head(`① 学ぶ｜${s.t}`,()=>sciHome333(s.g,s.t,s.term));A.append(e("div","card lesson",`<h2>📘 教科書のポイント</h2>${sciVisual333(s.g,s.t)}<p>${sciEsc333(d.learn)}</p><p>${sciEsc333(d.extra)}</p>`));A.append(e("div","card lesson",`<h2>🔎 観察・実験で確かめる</h2><p><b>問題・予想</b><br>${sciEsc333(d.predict)}</p><p><b>調べ方</b><br>${sciEsc333(d.observe)}</p><p><b>結果</b><br>${sciEsc333(d.result)}</p><p><b>結果から考える</b><br>${sciEsc333(d.think)}</p>`));if(d.terms.length)A.append(e("div","card",`<h2>🧠 覚えておきたいことば</h2>${d.terms.map(x=>`<p><b>${sciEsc333(x[0])}</b><br>${sciEsc333(x[1])}</p>`).join("")}`));A.append(btn("🔊 説明を聞く",()=>speakJP(`${s.t}。${d.learn}。${d.extra}。観察実験。${d.observe}。結果。${d.result}。考える。${d.think}`),"soft"));A.append(btn("➡️ ② 一緒に確認",sciTogether333,"primary"))}
function sciTogether333(){let s=sci333,d=s.d;head(`② 一緒に確認｜${s.t}`,sciLearn333);A.append(e("div","card lesson",`<h2>🤝 いっしょに整理</h2><p><b>1．何を調べる？</b><br>${sciEsc333(d.predict)}</p><p><b>2．どう調べる？</b><br>${sciEsc333(d.observe)}</p><p><b>3．何が分かった？</b><br>${sciEsc333(d.result)}</p><p><b>4．結果から何が言える？</b><br>${sciEsc333(d.think)}</p><p class="tiny">単元テストでは「知識」だけでなく、実験方法・結果・考察もよく確認します。</p>`));A.append(btn("➡️ ③ 自分で確認",sciPractice333,"primary"))}
function sciPracticeQs333(){let s=sci333,d=s.d;if(d.oldqs&&d.oldqs.length>=3)return d.oldqs.slice(0,3).map(q=>[q[0],q[1],q[2],d.think]);return [["この単元で調べる問いとして合っているのは？",[d.predict,"答えを先に決める","何も観察しない"],0,d.predict],["観察・実験の方法として合っているのは？",[d.observe,"結果に合わせて記録を変える","毎回まったく違う条件で比べる"],0,d.observe],["結果から考えられることは？",[d.think,"予想だけを正解にする","結果を見ずに終わる"],0,d.think]]}
function sciPractice333(){let s=sci333,qs=sciPracticeQs333();if(s.p>=3){s.p=0;head(`③ 確認できました｜${s.t}`,()=>sciHome333(s.g,s.t,s.term));A.append(e("div","card good","<h2>3問できました 🌱</h2><p>次は、単元テスト10問で確認できます。</p>"));A.append(btn("📝 単元テストへ",sciTestStart333,"primary"));return}let q=qs[s.p];head(`③ 自分で確認｜${s.t}`,sciTogether333);A.append(e("div","tiny",`${s.p+1} / 3`));A.append(e("div","card",`<h2>${sciEsc333(q[0])}</h2>`));let order=s.p===0?[0,1,2]:s.p===1?[1,0,2]:[2,1,0];order.forEach(n=>A.append(btn(q[1][n],()=>{if(n===q[2]){s.p++;if(window.ponoCorrectSound)window.ponoCorrectSound();sciPractice333()}else A.prepend(e("div","feedback warn",`🌱 ${sciEsc333(q[3])}`))},"soft")));A.append(btn("📘 ① 学ぶに戻る",sciLearn333,"ghost"))}
function sciDistractor333(g,t,field,offset){let keys=Object.keys(SCI_EXTRA333).filter(k=>k.startsWith(g+"|")&&k!==g+"|"+t);let k=keys[(Math.abs(t.length+offset*7))%keys.length],ot=k.split("|")[1],ob=sciBase333(g,ot);return ob&&ob[field]?ob[field]:"別の単元の内容"}
function sciBuildTest333(){let s=sci333,d=s.d,qs=[];let pqs=sciPracticeQs333();qs.push(...pqs.map(q=>[q[0],q[1].slice(),q[2],q[3],"知識"]));if(d.terms.length){d.terms.slice(0,2).forEach((x,i)=>qs.push([`「${x[0]}」の説明として正しいものは？`,[x[1],d.terms[(i+1)%d.terms.length]?.[1]||sciDistractor333(s.g,s.t,"think",i),sciDistractor333(s.g,s.t,"learn",i)],0,x[1],"ことば"]))}else{qs.push(["この単元の大切な内容は？",[d.learn,sciDistractor333(s.g,s.t,"learn",1),sciDistractor333(s.g,s.t,"learn",2)],0,d.learn,"知識"]);qs.push(["この単元のまとめとして合っているのは？",[d.extra,sciDistractor333(s.g,s.t,"think",1),sciDistractor333(s.g,s.t,"think",2)],0,d.extra,"知識"])}qs.push(["観察・実験の方法として最も適切なのは？",[d.observe,sciDistractor333(s.g,s.t,"observe",1),"予想に合うように条件を変え続ける"],0,d.observe,"観察・実験"]);qs.push(["観察・実験の結果として適切なのは？",[d.result,sciDistractor333(s.g,s.t,"result",1),sciDistractor333(s.g,s.t,"result",2)],0,d.result,"結果"]);qs.push(["結果から考えられることとして適切なのは？",[d.think,sciDistractor333(s.g,s.t,"think",1),"結果を見ず、最初の予想だけで決める"],0,d.think,"考察"]);qs.push(["この単元で考える問題として合っているのは？",[d.predict,sciDistractor333(s.g,s.t,"predict",1),sciDistractor333(s.g,s.t,"predict",2)],0,d.predict,"活用"]);while(qs.length<10)qs.push(["この単元の説明として正しいものは？",[d.extra,sciDistractor333(s.g,s.t,"learn",qs.length),sciDistractor333(s.g,s.t,"think",qs.length+1)],0,d.extra,"まとめ"]);return qs.slice(0,10)}
function sciTestStart333(){let s=sci333;s.testI=0;s.testOk=0;s.mist=[];s.qs=sciBuildTest333();s.start=Date.now();s.saved=false;sciTestQ333()}
function sciTestQ333(){let s=sci333,q=s.qs[s.testI];if(!q){sciTestSummary333();return}head(`📝 単元テスト｜${s.t}`,()=>sciHome333(s.g,s.t,s.term));A.append(e("div","tiny",`${s.testI+1} / 10　<span class="pill">${q[4]}</span>`));A.append(e("div","card",`<h2>${sciEsc333(q[0])}</h2>`));let order=s.testI%3===0?[0,1,2]:s.testI%3===1?[1,2,0]:[2,0,1];order.forEach(n=>A.append(btn(q[1][n],()=>sciTestAns333(n),"soft")))}
function sciTestAns333(n){let s=sci333,q=s.qs[s.testI],ok=n===q[2];if(ok){s.testOk++;if(window.ponoCorrectSound)window.ponoCorrectSound()}else s.mist.push({q:q[0],a:q[1][q[2]],e:q[3],k:q[4]});head(`${ok?"○":"確認"}｜${s.t}`,()=>sciHome333(s.g,s.t,s.term));A.append(e("div",`card ${ok?"good":"warn"}`,`<h2>${ok?"できました":"ここを確認"}</h2><p><b>答え：</b>${sciEsc333(q[1][q[2]])}</p><p>${sciEsc333(q[3])}</p>`));s.testI++;A.append(btn(s.testI<10?"次の問題へ":"結果を見る",s.testI<10?sciTestQ333:sciTestSummary333,"primary"))}
function sciTestSummary333(){let s=sci333,rate=Math.round(s.testOk/10*100);if(!s.saved){records.push({studentId:profile.id,date:new Date().toISOString(),subject:"理科",grade:s.g,unit:s.t,content:"理科 単元テスト 10問",rate,correct:s.testOk,total:10,seconds:Math.round((Date.now()-s.start)/1000),hints:0,status:rate>=80?"自力でできた":"練習中",next:rate>=80?"定着確認":"①学ぶを見直して再確認",process:"教科書内容に沿った単元テスト",questionStructure:"知識・ことば・観察実験・結果・考察・活用"});save();s.saved=true}head(`単元テスト結果｜${s.t}`,()=>sciHome333(s.g,s.t,s.term));A.append(e("div",`card ${rate>=80?"good":"warn"}`,`<h2>${s.testOk} / 10（${rate}%）</h2><p>${rate>=80?"大切な内容を確認できました。":"間違えたところを①学ぶで確認して、もう一度やってみよう。"}</p>`));if(s.mist.length)A.append(e("div","card",`<h2>🔎 もう一度確認</h2>${s.mist.map(m=>`<p><span class="pill">${m.k}</span><br><b>${sciEsc333(m.q)}</b><br>答え：${sciEsc333(m.a)}<br><span class="tiny">${sciEsc333(m.e)}</span></p>`).join("")}`));if(typeof ponoUnitReflection==="function")A.append(btn("🌱 単元ふりかえり",()=>ponoUnitReflection("理科",s.t,()=>subjectGradeTerms("理科",s.g)),"soft"));A.append(btn("📘 ① 学ぶを見直す",sciLearn333,"soft"));A.append(btn("🔁 単元テストをもう一度",sciTestStart333,"primary"));A.append(btn("単元一覧へ",()=>subjectGradeTerms("理科",s.g),"ghost"))}
const oldTUH333=textbookUnitHome;textbookUnitHome=function(sub,g,title,term){if(sub==="理科"&&g>=3&&g<=6&&sciData333(g,title)){sciHome333(g,title,term);return}return oldTUH333(sub,g,title,term)};
