
const A=document.getElementById("app"),RK="ponoV9Records",PK="ponoV9Plans",SK="ponoV9Student";
let profile=JSON.parse(localStorage.getItem(SK)||'{"id":"PONO001","name":"はるさん","grade":3}');
let records=JSON.parse(localStorage.getItem(RK)||"[]"),subject="",qi=0,S={};
const subs=["国語","算数","理科","社会","外国語活動"];
const B={
"国語":[["文の中で「なぜ」に答える部分を探す時の手がかりは？",["理由を表す言葉","文字の大きさ","ページ番号"],0,"理由を表す言葉や前後の文を確認します。"],["「森」の読みは？",["もり","かわ","そら"],0,"漢字の読みを確認します。"],["『雨が降ったので傘をさした。』理由は？",["雨が降ったから","暑いから","夜だから"],0,"理由を文から見つけます。"],["『本を読んでから感想を書いた。』後にしたことは？",["読む","感想を書く","買う"],1,"順序を確認します。"],["『プレゼントをもらい、にっこりした。』気持ちは？",["うれしい","こわい","かなしい"],0,"行動から気持ちを考えます。"]],
"算数":[["6×4は？",["20","24","28"],1,"九九はわり算の土台です。"],["12÷3は？",["3","4","6"],1,"同じ数ずつ分けます。"],["15個を5人で同じ数ずつ分けると？",["2個","3個","5個"],1,"場面をわり算に結びつけます。"],["1mは何cm？",["10","100","1000"],1,"長さの単位を確認します。"],["1/2は？",["2つに等分した1つ分","3つに等分した1つ分","全部"],0,"分数の意味を確認します。"]],
"理科":[["昆虫のあしは？",["4本","6本","8本"],1,"昆虫の体を確認します。"],["植物の育ちに大切なのは？",["光や水","石だけ","音だけ"],0,"植物の育ちを確認します。"],["磁石につきやすいのは？",["鉄","紙","木"],0,"磁石の性質です。"],["音が出る物で感じることがあるのは？",["ふるえ","色だけ","重さだけ"],0,"音と振動を結びつけます。"],["豆電球が光るには？",["回路がつながる","紙を置く","水につける"],0,"電気の通り道です。"]],
"社会":[["地図で方位を知るものは？",["方位記号","温度計","ものさしだけ"],0,"地図の基本です。"],["上が北なら右は？",["東","西","南"],0,"方位を確認します。"],["店の工夫を知るには？",["見学や聞き取り","想像だけ","何も見ない"],0,"地域調査の方法です。"],["火事の時に活動するのは？",["消防","図書館","美術館"],0,"地域の安全を守る仕組みです。"],["昔と今を比べる資料は？",["古い写真や地図","白紙","未来だけ"],0,"地域の変化を調べます。"]],
"外国語活動":[["Hello. は？",["こんにちは","さようなら","おやすみ"],0,"基本のあいさつです。"],["three は？",["2","3","4"],1,"数の表現です。"],["red は？",["赤","青","緑"],0,"色の表現です。"],["dog は？",["犬","猫","鳥"],0,"動物の表現です。"],["My name is Ken. は？",["私の名前はケンです","3歳です","犬が好きです"],0,"名前を伝える表現です。"]]};
function e(t,c,h){let x=document.createElement(t);if(c)x.className=c;if(h!==undefined)x.innerHTML=h;return x}
function btn(t,f,c=""){let b=e("button",c,t);b.onclick=f;return b}
function head(t,b){A.innerHTML="";let d=e("div","top");if(b)d.append(btn("← 戻る",b,"back"));d.append(e("h1","",t));A.append(d)}
function save(){localStorage.setItem(RK,JSON.stringify(records))}
function home(){head("🌱 Pono Learning Quest");A.append(e("p","sub","在籍学年を目安にスタートし、理解に合わせて必要なところを確認します。"));A.append(btn("🧒 子ども　今日の学習",child,"primary"));A.append(btn("🏠 保護者　自分の子の学び",parent));A.append(btn("📝 先生・Pono　時間割・提出用",teacher))}
function child(){head("🧒 今日の学習",home);let c=e("div","card",`<h2>${profile.name}</h2><p>在籍学年を学習開始の目安にします。</p>`),sel=e("select");for(let g=1;g<=6;g++){let o=e("option","",`小学${g}年`);o.value=g;sel.append(o)}sel.value=profile.grade;sel.onchange=()=>{profile.grade=+sel.value;localStorage.setItem(SK,JSON.stringify(profile));};c.append(sel,e("p","tiny","※学年はスタートの目安です。必要なら前の内容を確認し、理解できたら元の学習へ戻ります。"));A.append(c);let g=e("div","grid");subs.forEach(s=>g.append(btn(s,()=>start(s))));A.append(g)}
function start(s){subject=s;qi=0;S={ok:0,h:0,r:0,u:0,start:Date.now(),startGrade:profile.grade,route:[]};question()}
function question(){head(`${subject}｜確認`,child);let q=B[subject][qi];if(!q)return finish();A.append(e("div","tiny",`${qi+1}/${B[subject].length}　開始目安：小学${S.startGrade}年`));A.append(e("div","card",`<h2>${q[0]}</h2>`));A.append(btn("🔊 問題をきく",()=>{S.r++;let u=new SpeechSynthesisUtterance(q[0].replaceAll("÷","わる").replaceAll("×","かける"));u.lang="ja-JP";u.rate=.86;speechSynthesis.cancel();speechSynthesis.speak(u)},"soft"));q[1].forEach((x,i)=>A.append(btn(x,()=>answer(i===q[2],q[3]))));A.append(btn("💡 ヒント・説明を見る",()=>help(q[3],false),"soft"));A.append(btn("🌱 わからない・説明を見る",()=>help(q[3],true),"soft"))}
function help(x,unk){S.h++;if(unk)S.u++;document.querySelectorAll(".feedback").forEach(x=>x.remove());A.append(e("div","feedback",`<b>一緒に確認</b><br>${x}<br><span class="tiny">確認してから、もう一度挑戦して大丈夫です。</span>`))}
function answer(ok,x){if(ok){S.ok++;new Audio("correct.wav").play().catch(()=>{});A.append(e("div","feedback","✨ できた！"));setTimeout(()=>{qi++;question()},650)}else{S.h++;A.append(e("div","feedback warn",`🌱 ここを確認してみよう<br><span class="tiny">${x}</span>`))}}
function finish(){let n=B[subject].length,rate=Math.round(S.ok/n*100),sec=Math.round((Date.now()-S.start)/1000);let next=rate>=90&&S.h<=1?"現在の学年を目安に少し発展":rate>=60?"今の内容をもう一度確認":"必要な既習内容を確認してから戻る";let process=S.h? "説明・確認を使って再挑戦":"自力で取り組み";records.push({studentId:profile.id,date:new Date().toISOString(),subject,grade:profile.grade,rate,hints:S.h,reads:S.r,unknown:S.u,seconds:sec,next,process});save();head("✨ 学習記録",child);A.append(e("div","card",`<h2>取り組めました</h2><p>${subject} ${n}問</p><p>${process}</p><p><b>次：</b>${next}</p><p class="tiny">前の内容を確認することも「遅れ」ではなく、次につなげる学習として記録します。</p>`))}
function myRecords(){return records.filter(r=>r.studentId===profile.id)}
function parent(){head("🏠 学びのようす",home);let rr=myRecords().slice(-7),last=rr.at(-1),mins=Math.round(rr.reduce((a,r)=>a+r.seconds,0)/60);A.append(e("div","card",`<h2>${profile.name}の今週</h2><span class="pill">${rr.length}回</span><span class="pill">約${mins}分</span><p>${!last?"まだ記録はありません。":last.hints?`${last.subject}では、必要な説明を確認しながら再挑戦できました。`:`${last.subject}に自分で取り組めました。`}</p>`));A.append(e("div","card",`<h2>🌱 どんなふうに学べている？</h2><p>${!last?"学習を始めると、ここに学び方の変化が表示されます。":`${last.process} → ${last.next}`}</p><p class="tiny">点数だけでなく、説明を見る・読み上げを使う・分からないと伝える・再挑戦することも記録します。</p>`));A.append(e("div","card",`<h2>次のおすすめ</h2><p>${last?last.next:"興味のある教科から始めます。"}</p><p class="tiny">本番では保護者ログインに紐づくお子さんの記録だけを表示します。</p>`))}
function teacher(){head("📝 先生・Pono",home);A.append(btn("📅 今週の時間割を作る",plan,"primary"));A.append(btn("👥 生徒の現在地・達成状況",()=>{head("👥 生徒の現在地",teacher);let r=myRecords(),l=r.at(-1);A.append(e("div","card",`<b>${profile.name}</b>｜在籍 小学${profile.grade}年<br><span class="pill">${!l?"未確認":l.rate>=90&&l.hints<=1?"自力でできた":l.hints?"練習中":"取り組み中"}</span><p>${l?`${l.subject}：${l.process}<br>次：${l.next}`:"記録はまだありません。"}</p>`))}));A.append(btn("📄 学校提出用を自動作成",report));A.append(e("p","tiny","試作版はこの端末のブラウザ内保存です。本番では子ども・保護者・先生の認証と権限を分けます。"))}
function plan(){head("📅 今週の時間割",teacher);let p=JSON.parse(localStorage.getItem(PK)||"{}");["月","火","水","木","金"].forEach((d,i)=>{let c=e("div","card");c.append(e("b","",d+"曜日"));let s=e("select");subs.forEach(x=>s.append(e("option","",x)));s.value=(p[d]||{}).s||subs[i];let u=e("input");u.value=(p[d]||{}).u||"おすすめ単元";c.append(s,u);c.dataset.d=d;A.append(c)});A.append(btn("✓ 保存",()=>{let p={};document.querySelectorAll("[data-d]").forEach(c=>p[c.dataset.d]={s:c.querySelector("select").value,u:c.querySelector("input").value});localStorage.setItem(PK,JSON.stringify(p));alert("保存しました")},"primary"))}
function report(){head("📄 学校提出用",teacher);let rr=myRecords().slice(-20);A.append(e("div","card",`<b>${profile.name}</b>｜在籍 小学${profile.grade}年<br><span class="tiny">記録から下書きを作ります。</span>`));A.append(btn("✨ 下書きを自動作成",()=>{let mins=Math.round(rr.reduce((a,r)=>a+r.seconds,0)/60),subs2=[...new Set(rr.map(r=>r.subject))].join("・")||"―",back=rr.some(r=>r.next.includes("既習"));let d=e("div","card generated");d.innerHTML=`<h2>学習経過・学校共有用</h2><p>取組 ${rr.length}回／約${mins}分　教科：${subs2}</p>`;let ta=e("textarea");ta.value=rr.length?`本人の理解状況に合わせて学習に取り組んだ。${back?"必要に応じて既習内容を確認し、基礎を整理してから現在の学習につなげている。":"現在の理解を確認しながら、自力で取り組める範囲を広げている。"} 説明や読み上げも必要に応じて活用し、分からない時に確認して再挑戦する過程がみられた。`:"期間内の学習記録はまだありません。";d.append(ta);let s=e("select");["継続して取り組む","既習内容を確認しながら進める","理解が安定してきている","読み上げ等を活用すると理解しやすい"].forEach(x=>s.append(e("option","",x)));d.append(s,btn("🖨️ この生徒だけ印刷 / PDF",()=>window.print(),"primary noPrint"));A.append(d)},"primary"))}
home();
